### ISSUE TITLE
deployed chart -  undefined_endpoint

### ISSUE THREAD

**Issue by lachnerd** [openfga/helm-charts#113]
After Deploying the chart all i see is 

"{"code":"undefined_endpoint","message":"Not Found"}"

by opening the browser on the ingress hosts urls this seems not correct ?

**Comment by rhamzeh** [comment]
Hi @lachnerd - OpenFGA is an API, and serves nothing at the default `GET /`, try `GET /healthz` or `GET /stores`

This is the list of our API endpoints: https://openfga.dev/api/service

We also have a [CLI](https://github.com/openfga/cli) that can help you interact with the API quickly
