### ISSUE TITLE
Allow migration job setup without requiring embedded database

### ISSUE THREAD

**Issue by kdubb** [openfga/helm-charts#28]
Sometimes our PostgreSQL instance is already provided, we do not need to enable the sub-chart in this case.  Unfortunately that disables the migration job and the init container that waits for the job to finish.

Currently we literally recreate the job and init container as it is in the chart. It would be great if we could just enable the migration for a database that already exists.

**Comment by jpadilla** [comment]
this should have been resolved by https://github.com/openfga/helm-charts/pull/34
