### ISSUE TITLE
How to configure some of the newer OpenFGA env variables using this Helm chart?

### ISSUE THREAD

**Issue by patricknick** [openfga/helm-charts#60]
OpenFGA released a few new ENV Variables in [the latest releases](https://github.com/openfga/openfga/releases), for example `OPENFGA_MAX_CONCURRENT_READS_FOR_LIST_OBJECTS` or `OPENFGA_CHECK_QUERY_CACHE_ENABLED`. 

This helm chart allows to pull never versions of OpenFGA by setting the `image.tag=...`. However, I couldn't find a way how to set the newer env variables (I ended up using `kubectl` to manually set it on the deployment as a temporary workaround). 

Would it make sense to introduce a new Helm value that allows setting any env variable in the OpenFGA containers? This would help a lot when one is experimenting with newer features that are not yet integrated into the Helm chart. Or would it be possible to release new Helm chart versions alongside new OpenFGA versions?

**Comment by jpadilla** [comment]
@patricknick we'll include some of the newer knobs on the next release. There was also this change which should allow for more flexibility here as well https://github.com/openfga/helm-charts/pull/49
