### ISSUE TITLE
Issue with HorizontalPodAutoscaler apiVersion

### ISSUE THREAD

**Issue by jliedy** [openfga/helm-charts#65]
Helm is choking on deploying the chart due to autoscaling/v2beta1 being removed as of  Kubernetes v1.25:
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125

The apiVersion autoscaling/v2 has been available since Kubernetes v1.23.

I'll submit a pull request with an updated template.

**Comment by jon-whit** [comment]
@jliedy thanks for reporting. Taking a look now.

**Comment by jliedy** [comment]
Hey, I've submitted pull request #67 .  The new API requires a structure change to the spec.

**Comment by jliedy** [comment]
Awesome.  I've tested this in my k8s cluster and the HPA is getting created appropriately.  Thanks for the quick merge!
